package de.fotomarburg.lido2crm.ontology;

import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from C:\ont\cidoc_crm_pc.rdfs 
 * @author Auto-generated by schemagen on 08 Nov 2016 09:06 
 */
public class CIDOC_CRM_PC {
	
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.cidoc-crm.org/cidoc-crm-pc/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final OntProperty P01_has_domain = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P01_has_domain" );
    
    public static final OntProperty P01i_is_domain_of = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P01i_is_domain_of" );
    
    public static final OntProperty P02_has_range = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P02_has_range" );
    
    public static final OntProperty P02i_is_range_of = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P02i_is_range_of" );
    
    public static final OntProperty P03_has_range_literal = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P03_has_range_literal" );
    
    public static final OntProperty P102_1_has_type = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P102.1_has_type" );
    
    public static final OntProperty P107_1_kind_of_member = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P107.1_kind_of_member" );
    
    public static final OntProperty P130_1_kind_of_similarity = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P130.1_kind_of_similarity" );
    
    public static final OntProperty P136_1_in_the_taxonomic_role = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P136.1_in_the_taxonomic_role" );
    
    public static final OntProperty P137_1_in_the_taxonomic_role = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P137.1_in_the_taxonomic_role" );
    
    public static final OntProperty P138_1_mode_of_representation = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P138.1_mode_of_representation" );
    
    public static final OntProperty P139_1_has_type = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P139.1_has_type" );
    
    public static final OntProperty P14_1_in_the_role_of = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P14.1_in_the_role_of" );
    
    public static final OntProperty P144_1_kind_of_member = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P144.1_kind_of_member" );
    
    public static final OntProperty P16_1_mode_of_use = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P16.1_mode_of_use" );
    
    public static final OntProperty P19_1_mode_of_use = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P19.1_mode_of_use" );
    
    public static final OntProperty P3_1_has_type = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P3.1_has_type" );
    
    public static final OntProperty P62_1_mode_of_depiction = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P62.1_mode_of_depiction" );
    
    public static final OntProperty P67_1_has_type = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P67.1_has_type" );
    
    public static final OntProperty P69_1_has_type = m_model.createOntProperty( "http://www.cidoc-crm.org/cidoc-crm/P69.1_has_type" );
    
    /** <p></p> */
    public static final OntClass PC0_CRM_Property = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC0_CRM_Property" );
    
    /** <p></p> */
    public static final OntClass PC102_has_title = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC102_has_title" );
    
    /** <p></p> */
    public static final OntClass PC107_has_current_or_former_member = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC107_has_current_or_former_member" );
    
    /** <p></p> */
    public static final OntClass PC130_shows_features_of = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC130_shows_features_of" );
    
    /** <p></p> */
    public static final OntClass PC136_was_based_on = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC136_was_based_on" );
    
    /** <p></p> */
    public static final OntClass PC137_exemplifies = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC137_exemplifies" );
    
    /** <p></p> */
    public static final OntClass PC138_represents = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC138_represents" );
    
    /** <p></p> */
    public static final OntClass PC139_has_alternative_form = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC139_has_alternative_form" );
    
    /** <p></p> */
    public static final OntClass PC144_joined_with = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC144_joined_with" );
    
    /** <p></p> */
    public static final OntClass PC14_carried_out_by = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC14_carried_out_by" );
    
    /** <p></p> */
    public static final OntClass PC16_used_specific_object = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC16_used_specific_object" );
    
    /** <p></p> */
    public static final OntClass PC19_was_intended_use_of = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC19_was_intended_use_of" );
    
    /** <p></p> */
    public static final OntClass PC3_has_note = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC3_has_note" );
    
    /** <p></p> */
    public static final OntClass PC62_depicts = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC62_depicts" );
    
    /** <p></p> */
    public static final OntClass PC67_refers_to = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC67_refers_to" );
    
    /** <p></p> */
    public static final OntClass PC69_is_associated_with = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC69_is_associated_with" );
    
    /** <p></p> */
    public static final OntClass PC11_had_participant = m_model.createClass( "http://www.cidoc-crm.org/cidoc-crm/PC14_carried_out_by" );
    
}
